# Generated by Django 3.1.2 on 2020-10-29 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('resolution', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('detectionclass', models.CharField(max_length=32)),
                ('accuracy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('position_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lens_node.endpoint')),
            ],
        ),
    ]
