# Generated by Django 3.1.2 on 2020-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens_node', '0002_auto_20201108_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
